<% project_name = 'project2project2backend' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= project_name %>_development

test:
  <<: *default
  database: <%= project_name %>_test
